Add files via upload
sashaaladko/itirod pull request #2
Opened 2022-05-08 18:03 UTC by sashaaladko

2022-05-08 18:06 UTC, sashaaladko commented
https://sashaaladko.github.io/

2022-05-10 14:05 UTC, sashaaladko commented
Я знаю, что у меня много недочётов и не реализована адаптивная верстка, хотя на ноуте и телефоне смотрится терпимо, я бы хотела у вас попросить, чтобы вы указали на все мои недочёты и снизили за них баллы и дали функции для 4 лабы, если так можно, потому что я очень боюсь, что я не успею всё доделать до экзамена и не допущусь.

2022-05-12 10:50 UTC, katetushkan commented
создавать папки и загружать туда фото,
добавлять фото к себе от другого пользователя,
страница пользователя

That's ur functions for a 4th lab.

2022-05-12 11:07 UTC, katetushkan requested changes

2022-05-12 11:07 UTC, katetushkan commented on reg.css
> +body {
looks like duplicated code for me

2022-05-12 11:07 UTC, katetushkan commented on script.js
> +btn.onclick = function() {
use classes for this

2022-05-12 11:07 UTC, katetushkan commented on start.css
> +  .container {
format ur code.

2022-05-12 11:07 UTC, katetushkan commented on start.html
> +            <h2>Name the folder</h2>
h2 can't go before h1

2022-05-12 11:07 UTC, katetushkan commented on start.html
> +            <h2>Name the folder</h2>
it should be `label` for the `input`

2022-05-12 11:07 UTC, katetushkan commented on start.html
> +          <div class="modal-body">
u don't need additional wrapper for it.

2022-05-12 11:07 UTC, katetushkan commented on start.html
> +          <div class="modal-footer">
if it's `footer` so make it `<footer>`

2022-05-12 11:07 UTC, katetushkan commented on start.html
> +          <div class="photo">
use more specific tag

2022-05-12 11:07 UTC, katetushkan commented on start.html
> +        <div class="socials">
more specific tag would be nice here

2022-05-12 11:07 UTC, katetushkan commented on style.css
> +    background-color: rgba(93, 199, 97,0.7);
why not hex?

2022-05-12 11:08 UTC, katetushkan commented
<img width="606" alt="Screenshot 2022-05-12 at 13 08 06" src="https://user-images.githubusercontent.com/43992068/168058243-2498c436-9643-4aed-8b72-33c567d64692.png">
not terpimo.

2022-05-20 00:20 UTC, closed without merging